### ISSUE TITLE
X-Plat dev with WTS & Xamarin.Forms

### ISSUE THREAD

**Issue by mrlacey** [microsoft/TemplateStudio#2274]
_This is a working item and will be updated. The intention of this issue is to centrally document all that will be involved in adding support for Xamarin.Forms._

# Xamarin & WTS

Much of what is listed here is dependent upon the multi-project support work (#2252) being done for v3.0. The functionality detailed here will be released in a version after 3.0 but the exact timeline for the release of this functionality is yet to be determined.
The development of new UWP specific functionality will continue in tandem with the work done to support cross-platform (X-Plat) development with Xamarin.Forms (XF).

## Overriding principles

- WTS is a Windows-first tool.
- The aim of adding Xamarin(.Forms) support to WTS is to help developers create first class Windows/UWP apps with supporting mobile apps.
- The aim is not to create a "Xamain[.Forms] Template Studio" which produces a single code base that can be compiled for any supported platform.
- What goes into the UWP project for a page/feature will be identical if creating a solution for just UWP or all 3 supported platforms.

## Things that will be possible

- Continue to support creating a UWP only app.
- Create a project/solution that includes a UWP app and an XF project with heads for Android and iOS.
- Take a UWP only app and add XF projects to the solution.

## Things that will not be possible
- Delete the UWP app/project from the solution and continue to add (via right-click) to the XF apps.
- XF project develpment in VB.
- Support for XF templates that do not support all three supported platforms.
- Choosing which platforms to include. The options are UWP only, or UWP, iOS, AND Android. Of course, if someone doesn't want the iOS or Android version they don't have to compile it.
-- Deleting unwanted heads is not encouraged.
-- Any additional heads that are manually added will be ignored.
- Adding functionality to the Mobile apps that do not have equivalent functionality in the UWP app.

## Creating a new project

- As per the existing version of WTS, under New Universal Project, allow creation of a UWP only app based on the UWP only templates.
- Under 'Cross Platform' add a new entry that will allow the creation of a new solution containing the projects for creating apps for 3 platforms.
-- This option will only include templates that can be applied to all 3 platforms.

## Adding to a previously created project

- The right-click menu option will only be available from the UWP project.
- If a UWP only project, it will be possible to add X-Plat support. This will add minimally populated XF projects. These new apps will be equivalent to if creating a new project and adding no extra pages & features.
- If adding to a X-Plat project, in addition to adding a page/feature for all 3 projects it will also be possible to add to just the UWP app and this will allow selecting from all UWP templates. (This will mean loading a different set of templates in the wizard.)

## Project/Solution structure

- There will be 5 projects in the solution
-- App.UWP (The UWP app)
-- App.Core (.Net Standard project containing platform agnostic code that is referenced by all other projects)
-- App.XamForms (.Net Standard project with shared XF functionality)
-- App.iOS (XF iOS head)
-- App.Android (XF Android Head)

## Questions that need answering BEFORE we build anything

- [ ] If one of the XF Heads is deleted, what should the warnings/errors be when adding a new page/feature? (Ignore the missing head? prevent adding at all? Show warnings in the summary page?)
- [ ] If take an existing UWP project with some pages and add X-Plat support, how to add XF versions of the existing UWP pages? (Do we just live with lots of warnings in the add summary window? or do something else/more?)
- [ ] What should the right-click menu structure look like for supporting all options?
- [ ] Should the X-Plat/XF templates folder include copies of the corresponding UWP templates? (If not, how are they kept in sync? Do we need any extra tools/scripts/tests to enable or enforce this?)
- [ ] What do we call the no-3rdparty-framework equivalent of 'MVVM Basic' for X-Plat solutions?
- [ ] What do we do if someone wants to add X-Plat support to a UWP only app that was created with CodeBehind or MVVMBasic? (May need different solutions for each.)

## Action points

- [ ] Answer above questions.
- [ ] Review (and document) which exisiting UWP templates could have XF equivalents & prioritize them.
- [ ] Plan (and document) template folder structure.
- [ ] Review (and document) required changes to Wizard and tooling to enable the functionality detailed here.

---

X-Ref: #312, & [wiki](https://github.com/Microsoft/WindowsTemplateStudio/wiki/Xamarin)

If you have concerns, questions, or strong opinions about any of the above, please comment below ASAP.

**Comment by touseefbsb** [comment]
apart from ios and android, XF also supports building for linux and macOs ( and web might also be included in future, though still ecperimentl with the ooui framework ) just wanted to put it out there as I think it will help in the decision of solution structure. :)

**Comment by crutkas** [comment]
@touseefbsb  our goal here is only iOS / Android direct output currently.

**Comment by touseefbsb** [comment]
@crutkas  oh alright

**Comment by ghuntley** [comment]
` App.Android` the "Android" name is reserved if I remember correctly. Check with the Xamarin.Android team if it's okay. I've been using `App.Droid` for 5+ years... it used to be a problem.. maybe it isn't anymore....

**Comment by mrlacey** [comment]
@ghuntley Standard Xamarin templates use the `App.Android` naming convention so I assume it's ok now. I remember using 'Droid' in the past but don't know when the change happened. Our aim is to match what a straight Xamarin.Forms template produces.

**Comment by pw3107** [comment]
Will the x-plat XAML be different for UWP/Xamarin or is XAML standard being considered?

**Comment by mrlacey** [comment]
>           Will the x-plat XAML be different for UWP/Xamarin or is XAML standard being considered?

There is no single "XAML standard" to consider yet. My understanding is that XAML Standard will lead to the same things being called the same thing on different versions of XAML, not that there will be one dialect of XAML that looks and behaves identically in all situations on both UWP & XF (& WPF).

The plan for this issue is that WTS will produce separate UWP and XF projects that do similar things but in their own ways and can share code/data/backends, etc. as much as possible.

**Comment by pw3107** [comment]
Matt, thanks for the reply and information.

Paul.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mrlacey** [comment]
The above listed plans are sooooooo old, I don't see any reason to keep this issue open.
For anyone interested in cross-platform support, have a look at https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.MauiAppAccelerator
