### ISSUE TITLE
Support templates from multiple sources

### ISSUE THREAD

**Issue by mrlacey** [microsoft/TemplateStudio#3391]
- [ ] Add UI for specifying the sources. (See below)
- [ ] Support retrieving template bundles from multiple locations. This needs to include checking for updates, retrying failed attempts, unzipping files if in a bundle, copying from other directories, and more.
- [ ] Handle combining templates from multiple folders (on the local machine.) The DotNetTemplating engine supports this but after a brief investigation, I was unable to get this to work from within the existing WTS code base.
- [ ] Improve error handling and reporting for invalid templates

These points will require further refinement and may be broken into further issues if implementation implemented by different people

---

Here's how configuration might work. (This is deliberately low fidelity as VS designer involvement will be necessary. All text is for example and not final copy.)

- Add a link to the configuration in the wizard.
 A similar link will also be needed in the AddItem wizard UI.

![Example of adding a link to a new settings/configuration view](https://user-images.githubusercontent.com/189547/66751789-ca16d380-ee87-11e9-8483-004b1fdc258b.png)

Managing the list of template sources within UI provided by the extension allows following current styling which is different from default VS UI.  
Not storing and managing this inside standard VS Options functionality also makes it easier to use this with VSEmulator. 

![image](https://user-images.githubusercontent.com/189547/66753663-34317780-ee8c-11e9-9c3f-90675df4226e.png)

1. The list is based on the wizard entry point and filtered as such (by platform and programming language). This is to avoid making this more complicated by not adding things people aren't using.
2. The default (what is currently included) can't be opted out from inclusion. Included in this list to make it clear that they are part of what will be made available in the UI.
3. Other templates also managed & hosted as part of this project are available and can be included/excluded by checking the option. When first introducing this functionality these should be checked by default.
4.  This can either be a URL to a zip file containing templates, or a file path to a directory containing templates. Empty entries will be removed when leaving the screen.
5. An option at the bottom to add more template sources.

After leaving this screen (navigating back) it will be necessary to refresh the list of available templates (if nothing has changed). This may result in previous selections being lost.

---

This is a follow on from #234

**Comment by mrlacey** [comment]
Provisionally assigning to 3.6 as work will begin during this period but is unlikely to ship with that release.

**Comment by sibille** [comment]
Agree that extracting Prism and Caliburn.Micro is a good first example, but this is a big issue and I'm not sure if we have bandwith in the 3.6 timeframe to properly focus on this.

**Comment by mrlacey** [comment]
I only said provisionally for 3.6 happy to bump to backlog if you'd rather not start something that can be finished in that release.

**Comment by mrlacey** [comment]
closing due to lack of demand from others.
It seems a few people have forked the whole project rather than trying to add or wait for this capability.
Plans relating to the restructure for VS2022 should also make it easier for anyone else wanting to fork and make their own version anyway.
