### ISSUE TITLE
Divide currently provided templates into separate downloads

### ISSUE THREAD

**Issue by mrlacey** [microsoft/TemplateStudio#3392]
- [ ] Split up current templates on disk so Prism & Caliburn.Micro templates can be installed separately.
- [ ] Split out ore specific templates that shouldn't be in the main bundle. XamlStyleConfig was added on the basis that it would be broken into an "additional" bundle once this capability was added. Having it in a separate bundle on its own probably isn't ideal and so may want to review when this is done or if there are other items that can also be moved out of the main bundle at this time.
- [ ] Configure default options in UI.
- [ ] Add processes for packaging and distributing multiple templates per platform/language.
- [ ] Enable templates from multiple sources to include items from other sources during composition.
- [ ] Enable templates from multiple sources to exclude items from other sources during composition.
- [ ] Update testing/validation of templates to account for different template locations.

These points will require further refinement/clarification and may be broken into further issues if implementation implemented by different people

---

This is a follow on from #234 and requires #3391 be implemented first

**Comment by mrlacey** [comment]
Current plans regarding the future of the project and how support for VS2022 is being added make this redundant.
