### ISSUE TITLE
Enable conditional checks in PR CI process

### ISSUE THREAD

**Issue by mrlacey** [microsoft/TemplateStudio#4441]
### Is your feature request related to a problem? Please describe.

We want PRs to be as fast as possible.
Currently, they build all the extensions and run "minimal" tests for each of them.
This is often unnecessary, as changes for the templates in one extension should not impact the other extensions.

We should make the following changes:

- [x] Reenable UWP testing as part of the PR process (see comment in `_build/pipelines/ci.yml`
- [x] Always run the Shared test steps if there are any changes in the `code` directory
- [x] Run only the **UWP** build and test jobs if changes are entirely contained within
    -  `code\TemplateStudioForUWP`
    -  `code\test\TemplateStudioForUWP.Tests` and
    -  `code\src\ProjectTemplates\UWP`
- [x] Run only the **WPF** build and test jobs if changes are entirely contained within
    -  `code\TemplateStudioForWPF`
    -  `code\test\TemplateStudioForWPF.Tests` and
    -  `code\src\ProjectTemplates\WPF`
- [x] Run only the **WinUICs** build and test jobs if changes are entirely contained within
    -  `code\TemplateStudioForWinUICs`
    -  `code\test\TemplateStudioForWinUICs.Tests` and
    -  `code\src\ProjectTemplates\WinUI\Cs`
- [x] Run only the **WinUICpp** build and test jobs if changes are entirely contained within
    -  `code\TemplateStudioForWinUICpp`
    -  `code\test\TemplateStudioForWinUICpp.Tests` and
    -  `code\src\ProjectTemplates\WinUI\Cpp`
- [x] If there are changes anywhere else in the `code` directory:
    - build everything
    - run all tests
- [x] for changes entirely limited to directories apart from `code` do not run any tests. (They won't do anything new.)

Additionally, 
- [x] apply similar logic to the nightly build script.

### Describe the solution you'd like

see above.

### Describe alternatives you've considered

🤷

### Additional context

Need to investigate how easy it will be to enforce the above-defined rules. 

### Applies to the following platforms:

- [X] WinUI
- [X] WPF
- [X] UWP

**Comment by mikebattista** [comment]
Triggers can only be set on pipelines not on jobs, so to implement this properly in the future, we'll likely need to split up pipelines like ci.yaml into separate pipelines per trigger ruleset.

**Comment by mrlacey** [comment]
> Triggers can only be set on pipelines not on jobs, so to implement this properly in the future, we'll likely need to split up pipelines like ci.yaml into separate pipelines per trigger ruleset.

I was initially disappointed by this restriction, but it will actually make configuration much easier. :)

**Comment by mikebattista** [comment]
@mrlacey, take a look at https://github.com/microsoft/TemplateStudio/tree/mikebattista/pipelines/_build/pipelines.

I tested the template pattern and triggers with the WinUICs pipeline then copied and replaced the parameters for the other extensions. The other pipelines should be correct as well assuming the triggers are defined correctly per your spec.

**Comment by mikebattista** [comment]
Merged with #4477 and subsequent fixes.

**Comment by mikebattista** [comment]
Actually it doesn't look like we can use path filters on scheduled pipelines per https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/schedules-cron?view=azure-pipelines. I'm also getting errors when trying to run the pipelines manually related to the path filters, which confirms this.

I'll need to remove the path filters on the nightly pipelines.
